plugins {
    id "java-library"
    id "idea"
    id "eclipse"
    id "net.neoforged.moddev" version "2.0.141"
}

group = mod_group_id
version = mod_version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = neo_version

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            systemProperty "forge.logging.markers", "REGISTRIES"
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }

        client {
            client()
        }

        server {
            server()
            programArgument "--nogui"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
        minecraft_version      : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version            : neo_version,
        neo_version_range      : neo_version_range,
        loader_version_range   : loader_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    filesMatching("META-INF/neoforge.mods.toml") {
        expand replaceProperties
    }
}
