org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.installations.auto-download=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.235
neo_version_range=[21.1.235,)
loader_version_range=[4,)

mod_id=techcraft_additions
mod_name=TechCraft: Additions
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=com.techcraft.additions
mod_authors=TechCraft
mod_description=Addon content for the local TechCraft Minecraft modpack.
